# Generated by Django 5.1.2 on 2024-10-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="api_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
